name: List Root Changed Directories

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-root-changed-dirs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3

    - name: List root changed directories
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | cut -d'/' -f1 | uniq

    - name: Bazel build release
      run: |
        bazel build //src/main:cpp_app --config=release
