name: List Root Changed Directories

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  list-root-changed-dirs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Необходимо для получения истории изменений

    - name: List root changed directories
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | cut -d'/' -f1 | uniq
